### PR TITLE
Fix compile errors

### PR DESCRIPTION
**Pull request by shadansari**
Signed-off-by: Shad Ansari <shad@onlab.us>

### CODE REVIEW

**Comment by ajhai** [comment]
@shadansari Thanks for the patch. I'm in the process of updating this repo to use gRPC 1.3.0. I will merge this PR once those changes are done and if this is still needed.

**Comment by kunchumraghu** [comment]
I tried to build GRPC-C as per the instruction in README and faced some compilation error. Later i took the changes mentioned by "Shadansari", still i see some compilation error. Below is the error which i am getting.

mv -f $depbase.Tpo $depbase.Po
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -I. -I./../third_party/protobuf-c -I./../third_party/protobuf-c/protobuf-c -g -O2   -o protoc-gen-grpc-c ../third_party/protobuf-c/protoc-c/c_bytes_field.o ../third_party/protobuf-c/protoc-c/c_enum.o ../third_party/protobuf-c/protoc-c/c_enum_field.o ../third_party/protobuf-c/protoc-c/c_extension.o ../third_party/protobuf-c/protoc-c/c_field.o ../third_party/protobuf-c/protoc-c/c_file.o ../third_party/protobuf-c/protoc-c/c_generator.o ../third_party/protobuf-c/protoc-c/c_helpers.o ../third_party/protobuf-c/protoc-c/c_message.o ../third_party/protobuf-c/protoc-c/c_message_field.o ../third_party/protobuf-c/protoc-c/c_primitive_field.o ../third_party/protobuf-c/protoc-c/c_service.o ../third_party/protobuf-c/protoc-c/c_string_field.o grpc_c_file.o grpc_c_generator.o grpc_c_helpers.o grpc_c_message.o grpc_c_service.o main.o /usr/local/lib/libprotobuf.a /usr/local/lib/libprotoc.a 
libtool: link: g++ -I. -I./../third_party/protobuf-c -I./../third_party/protobuf-c/protobuf-c -g -O2 -o protoc-gen-grpc-c ../third_party/protobuf-c/protoc-c/c_bytes_field.o ../third_party/protobuf-c/protoc-c/c_enum.o ../third_party/protobuf-c/protoc-c/c_enum_field.o ../third_party/protobuf-c/protoc-c/c_extension.o ../third_party/protobuf-c/protoc-c/c_field.o ../third_party/protobuf-c/protoc-c/c_file.o ../third_party/protobuf-c/protoc-c/c_generator.o ../third_party/protobuf-c/protoc-c/c_helpers.o ../third_party/protobuf-c/protoc-c/c_message.o ../third_party/protobuf-c/protoc-c/c_message_field.o ../third_party/protobuf-c/protoc-c/c_primitive_field.o ../third_party/protobuf-c/protoc-c/c_service.o ../third_party/protobuf-c/protoc-c/c_string_field.o grpc_c_file.o grpc_c_generator.o grpc_c_helpers.o grpc_c_message.o grpc_c_service.o main.o  /usr/local/lib/libprotobuf.a /usr/local/lib/libprotoc.a
make[2]: Leaving directory '/home/tibit/ATT/phase3/Broadcom/grcp_c_wrapper/grpc-c/compiler'
Making all in lib
make[2]: Entering directory '/home/tibit/ATT/phase3/Broadcom/grcp_c_wrapper/grpc-c/lib'
depbase=`echo client.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I. -I./h -I./../third_party/protobuf-c -g -O2 -MT client.lo -MD -MP -MF $depbase.Tpo -c -o client.lo client.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I./h -I./../third_party/protobuf-c -g -O2 -MT client.lo -MD -MP -MF .deps/client.Tpo -c client.c  -fPIC -DPIC -o .libs/client.o
client.c: In function ‘gc_client_request_status’:
client.c:276:2: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  = &context->gcc_status_details;
  ^
client.c:277:58: error: ‘struct <anonymous>’ has no member named ‘status_details_capacity’
     context->gcc_ops[op_count].data.recv_status_on_client.status_details_capacity 
                                                          ^
client.c: In function ‘gc_client_prepare_ops’:
client.c:756:6: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
      = &context->gcc_status_details;
      ^
client.c:757:55: error: ‘struct <anonymous>’ has no member named ‘status_details_capacity’
  context->gcc_ops[op_count].data.recv_status_on_client.status_details_capacity 
                                                       ^
client.c: In function ‘grpc_c_client_request_async’:
client.c:830:25: error: incompatible type for argument 5 of ‘grpc_channel_create_call’
        context->gcc_cq, method, 
                         ^
In file included from ./h/grpc-c/grpc-c.h:14:0,
                 from client.c:6:
/usr/local/include/grpc/grpc.h:179:20: note: expected ‘grpc_slice {aka struct grpc_slice}’ but argument is of type ‘const char *’
 GRPCAPI grpc_call *grpc_channel_create_call(
                    ^
client.c:831:8: warning: passing argument 6 of ‘grpc_channel_create_call’ from incompatible pointer type [-Wincompatible-pointer-types]
        client->gcc_host, 
        ^
In file included from ./h/grpc-c/grpc-c.h:14:0,
                 from client.c:6:
/usr/local/include/grpc/grpc.h:179:20: note: expected ‘const grpc_slice * {aka const struct grpc_slice *}’ but argument is of type ‘char *’
 GRPCAPI grpc_call *grpc_channel_create_call(
                    ^
client.c: In function ‘grpc_c_client_request_sync’:
client.c:887:25: error: incompatible type for argument 5 of ‘grpc_channel_create_call’
        context->gcc_cq, method, 
                         ^
In file included from ./h/grpc-c/grpc-c.h:14:0,
                 from client.c:6:
/usr/local/include/grpc/grpc.h:179:20: note: expected ‘grpc_slice {aka struct grpc_slice}’ but argument is of type ‘const char *’
 GRPCAPI grpc_call *grpc_channel_create_call(
                    ^
client.c:888:8: warning: passing argument 6 of ‘grpc_channel_create_call’ from incompatible pointer type [-Wincompatible-pointer-types]
        client->gcc_host, 
        ^
In file included from ./h/grpc-c/grpc-c.h:14:0,
                 from client.c:6:
/usr/local/include/grpc/grpc.h:179:20: note: expected ‘const grpc_slice * {aka const struct grpc_slice *}’ but argument is of type ‘char *’
 GRPCAPI grpc_call *grpc_channel_create_call(
                    ^
Makefile:479: recipe for target 'client.lo' failed
make[2]: *** [client.lo] Error 1
make[2]: Leaving directory '/home/tibit/ATT/phase3/Broadcom/grcp_c_wrapper/grpc-c/lib'
Makefile:464: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tibit/ATT/phase3/Broadcom/grcp_c_wrapper/grpc-c'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2

Can you please let me know what might have went wrong.

**Comment by ajhai** [comment]
@kunchumraghu What is the version of gRPC that you are using?

**Comment by kunchumraghu** [comment]
I am not sure how to get the version of gRPC which i am using. Below is the protoc --version output.

root@tibit-VirtualBox:/home/tibit# protoc --version
libprotoc 3.2.0
root@tibit-VirtualBox:/home/tibit# protoc-c --version
protobuf-c 1.2.1
libprotoc 2.6.1

Thanks and Regards
Raghu. S

**Comment by kunchumraghu** [comment]
@ajhai , The machine which i was using had already GRPC installed in it. In order to avoid confusion I reinstalled the machine with ubuntu 16.04 and installed all required component.  Even with fresh download i am facing the same compilation error. I don't see the parameter "status_details_capacity" in grpc_ops structure which is defined in "grpc_types.h" file. 
Since i am new and experimenting the usage of GRPC, not sure is that ok to comment the line in client.c and continue the compilation.

Below are the details of GRPC and protobuf. 

GRPC : v1.3.2. (Download using below procedure)
 $ git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init
 $ make
 $ [sudo] make install

Protobuf details : 
root@grpc-VirtualBox:/home/grpc/ATT/grpc-c# protoc --version
libprotoc 3.2.0
root@grpc-VirtualBox:/home/grpc/ATT/grpc-c# protoc-c --version
protobuf-c 1.2.1
libprotoc 3.2.0

**Comment by kunchumraghu** [comment]
@ajhai Finally, i could able to compile and execute the sample programs with grpc-1.1.4. 

Thanks and Regards
Raghu. S

**Comment by ashrithr** [comment]
Running into this issue, after applying this patch and compiling the examples:

```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -I. -I../../examples/../lib/h/ -I../../examples/../third_party/protobuf-c -I../../examples/../third_party/grpc/include -g -O2   -o foo_client foo_client.o foo.grpc-c.o ../lib/libgrpc-c.la /usr/local/lib/libgrpc.a /usr/local/lib/libgpr.a /usr/local/lib/libprotobuf-c.a -lpthread
libtool: link: gcc -I. -I../../examples/../lib/h/ -I../../examples/../third_party/protobuf-c -I../../examples/../third_party/grpc/include -g -O2 -o .libs/foo_client foo_client.o foo.grpc-c.o  ../lib/.libs/libgrpc-c.so /usr/local/lib/libgrpc.a /usr/local/lib/libgpr.a /usr/local/lib/libprotobuf-c.a -lpthread -Wl,-rpath -Wl,/usr/local/lib
../lib/.libs/libgrpc-c.so: undefined reference to `grpc_c_get_client_id_from_channel'
collect2: error: ld returned 1 exit status
make: *** [foo_client] Error 1
```

Dependency versions used:

gRPC - 1.1.x
protobuf - 3.0.x
protobuf-c - 1.2.1

**Comment by ajhai** [comment]
There have been lot of code that moved around and some got added. I updated everything to work with gRPC v1.3.0. Pushed the changes. Build should go through fine with 1.3.0. 

@ashrithr Could you please try with gRPC v1.3.0  and check?
